# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-01T18:31:55Z"
  labels:
    app: cryptgeon
  name: cryptgeon
spec:
  containers:
  - args:
    - redis-server
    - --maxmemory
    - 1gb
    - --maxmemory-policy
    - allkeys-lru
    image: docker.io/library/redis:latest
    name: redis
    volumeMounts:
    - mountPath: /data
      name: 8f4177575dd86c80a04c270e12d370f727043a8d18a0db158f577a8ce5f545b7-pvc
  - image: docker.io/cupcakearmy/cryptgeon:latest
    envFrom:
    - configMapRef:
        name: cryptgeon-config
        optional: false
    name: cryptgeon-container
  volumes:
  - name: 8f4177575dd86c80a04c270e12d370f727043a8d18a0db158f577a8ce5f545b7-pvc
    persistentVolumeClaim:
      claimName: 8f4177575dd86c80a04c270e12d370f727043a8d18a0db158f577a8ce5f545b7
