# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-02T09:27:31Z"
  labels:
    app: vpn
  name: vpn
spec:
  containers:
  - args:
    - /usr/bin/dumb-init
    - node
    - server.js
    envFrom:
    - configMapRef:
        name: vpn-config
        optional: false
    image: docker.io/weejewel/wg-easy:latest
    name: vpn-container
    ports:
    - containerPort: 51821
      hostPort: 51821
    - containerPort: 51820
      hostPort: 51820
      protocol: UDP
    securityContext:
      capabilities:
        add:
        - CAP_NET_ADMIN
        - CAP_SYS_MODULE
    volumeMounts:
    - mountPath: /etc/wireguard
      name: vpn-pvc
  volumes:
  - name: vpn-pvc
    persistentVolumeClaim:
      claimName: vpn
