# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-01T15:17:00Z"
  labels:
    app: bitwarden
  name: bitwarden
spec:
  containers:
  - image: docker.io/vaultwarden/server:latest
    name: bitwarden-container
    volumeMounts:
    - mountPath: /data
      name: home-cloud-nas-bitwarden-host-0
    envFrom:
    - configMapRef:
        name: bitwarden-config
        optional: false
  volumes:
  - hostPath:
      path: /home/cloud/nas/bitwarden
      type: Directory
    name: home-cloud-nas-bitwarden-host-0
